export const PRODUCT_TYPE = {
  ADD_PRODUCT_TYPE: "ADD_PRODUCT_TYPE",
  GET_PRODUCTS_TYPE: "GET_PRODUCTS_TYPE",
  PLUS_PRODUCT_TYPE: "PLUS_PRODUCT_TYPE",
  MINUS_PRODUCT_TYPE: "MINUS_PRODUCT_TYPE",
  DELETE_PRODUCT_TYPE: "DELETE_PRODUCT_TYPE",
  LOADING_PRODUCTS_TRUE: "LOADING_PRODUCTS_TRUE",
  LOADING_PRODUCTS_FALSE: "LOADING_PRODUCTS_FALSE",
};
